name: 'm&m ash'
repo: 'http://github.com/gaow/mvarbvs'
footer: "Copyright &copy 2016-2018 Gao Wang et al at Stephens Lab, University of Chicago"
include_dir: ['analysis', 'prototype', 'dsc', 'writeup']
homepage: "writeup/Overview.ipynb"
#release_message: "Build website via jnbinder"
#post_release_actions: "cd writeup/8858826xzvbppzrxmtw && git pull" 
reverse_autoindex: ['analysis', 'prototype', 'writeup'] 
password_file: .passwd
