name: 'm&m ash'
repo: 'http://github.com/gaow/mvarbvs'
footer: "&copy 2016-2017 Gao Wang et al at Stephens Lab, University of Chicago"
include_dir: ['analysis', 'pipeline', 'writeup']
homepage: "writeup/Overview.ipynb"
release_message: "Build website via jnbinder"
post_release_actions: "cd writeup/8858826xzvbppzrxmtw && git pull" 
reverse_autoindex: True
