hosts:
  localhost:
    address: localhost
    paths:
      home: /home/{user_name}
  midway2:
    account: ''
    address: gaow@midway2.rcc.uchicago.edu
    description: UChicago RCC cluster Midway 2
    job_template: '#!/bin/bash
      #SBATCH --time={walltime}
      #{partition}
      #{account}
      #SBATCH --nodes=1
      #SBATCH --ntasks-per-node={cores}
      #SBATCH --mem-per-cpu={mem//10**9}G
      #SBATCH --job-name={job_name}
      #SBATCH --output={cur_dir}/.sos/{job_name}.out
      #SBATCH --error={cur_dir}/.sos/{job_name}.err
      cd {cur_dir}
      module load R/3.4.3
      sos execute {task} -v {verbosity} -s {sig_mode}'
    kill_cmd: scancel {job_id}
    max_cores: 40
    max_mem: 64G
    max_running_jobs: 30
    max_walltime: '36:00:00'
    partition: SBATCH --partition=broadwl
    paths:
      home: /home/gaow
    queue_type: pbs
    status_check_interval: 60
    status_cmd: squeue --job {job_id}
    submit_cmd: sbatch {job_file}
    submit_cmd_output: Submitted batch job {job_id}
  midway2_head:
    account: ''
    address: localhost
    description: UChicago RCC cluster Midway 2
    job_template: '#!/bin/bash
      #SBATCH --time={walltime}
      #{partition}
      #{account}
      #SBATCH --nodes=1
      #SBATCH --ntasks-per-node={cores}
      #SBATCH --mem-per-cpu={mem//10**9}G
      #SBATCH --job-name={job_name}
      #SBATCH --output={cur_dir}/.sos/{job_name}.out
      #SBATCH --error={cur_dir}/.sos/{job_name}.err
      cd {cur_dir}
      module load R/3.4.3
      sos execute {task} -v {verbosity} -s {sig_mode}'
    kill_cmd: scancel {job_id}
    max_cores: 40
    max_mem: 64G
    max_running_jobs: 30
    max_walltime: '36:00:00'
    partition: SBATCH --partition=broadwl
    paths:
      home: /home/gaow
    queue_type: pbs
    status_check_interval: 60
    status_cmd: squeue --job {job_id}
    submit_cmd: sbatch {job_file}
    submit_cmd_output: Submitted batch job {job_id}
localhost: localhost
