---
title: gchromVAR analysis of SuSiE and mvSuSiE fine-mapping results for UK Biobank blood cell traits
author: Peter Carbonetto
date: October 23, 2023
output:
  html_document:
    theme: readable
    highlight: textmate
    lib_dir: site_libs
    self_contained: no
---

TO DO: Add summary of the [gchromvar][gchromvar] analysis here.

```{r knitr-opts, include=FALSE}
knitr::opts_chunk$set(comment = "#",collapse = TRUE,results = "hold",
                      fig.align = "center",dpi = 120)
```

Load the packages used in the analysis.

```{r load-pkgs, message=FALSE, warning=FALSE}
library(chromVAR)
library(gchromVAR)
library(BuenColors)
library(SummarizedExperiment)
library(data.table)
library(BiocParallel)
library(BSgenome.Hsapiens.UCSC.hg19)
library(ggplot2)
library(cowplot)
```

For reproducibility, set the seed.

```{r set-seed}
set.seed(1)
```

For a point of comparison, we will use the gchromVAR results from the
[Vuckovic *et al* paper][vuckovic-cell] (they were downloaded from
[here][vuckovic-github]):

```{r read-vuckovic-results}
celltypes <- c("B","CD4","CD8","CLP","CMP","Ery","GMP-A","GMP-B","GMP-C",
               "HSC","LMPP","mDC","Mega","MEP","mono","MPP","NK","pDC")
celltype_colors <- c(jdb_color_map(celltypes[1:11]),
                     c("yellow","hotpink"),
                     jdb_color_map(celltypes[14:18]))
vuckovic_traits <- c("rbc","mcv","hct","hgb","hlr","irf","mch","mchc","mrv",
                     "mscv","rdw_cv","ret","plt","mpv","pct","pdw","wbc",
					 "baso","eo","mono","neut","lymph")
vuckovic <- read.table("../data/vuckovic_gchromVAR_zscores_ukbb_v2.txt",
                       sep = "\t",header = TRUE,stringsAsFactors = FALSE)
vuckovic <- transform(vuckovic,
                      Celltype = factor(Celltype,celltypes),
					  Trait = factor(Trait,vuckovic_traits),
					  pval = pmin(pval,10))
```

This plot reproduces Fig. 3A from the Vuckovic *et al* paper.

```{r, fig.height=3, fig.width=3.5}
heatmap_colors <- c("#d7191c","#fdae61","#ffffbf","#abd9e9","#2c7bb6")
ggplot(vuckovic,
            aes(x = Celltype,y = Trait,fill = Celltype,size = pval)) +
  geom_point(shape = 21,color = "white") +
  scale_size(range = c(0.65,6)) +
  scale_fill_manual(values = celltype_colors,guide = "none") +
  guides(size = guide_legend(override.aes = list(shape = 21,fill = "black"))) +
  theme_cowplot(font_size = 9) +
  labs(x = "",y = "") +
  theme(axis.text.x = element_text(angle = 90,hjust = 1,vjust = 0.5))
```

This last code chunk is a record of the exact versions of the R
packages used to generate the results:

```{r session-info}
sessionInfo()
```

[gchromvar]: https://github.com/caleblareau/gchromVAR
[vuckovic-cell]: https://doi.org/10.1016/j.cell.2020.08.008
[vuckovic-github]: https://github.com/bloodcellgwas/manuscript_code
